import Head from "next/head";
import { Toaster } from "react-hot-toast";

export default function Home() {
  return (
    <>
      <Head>
        <title>TutorHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4 h-screen flex items-center justify-center">
        Hello from backend 🌱
        <Toaster />
      </main>
    </>
  );
}
